### ISSUE TITLE
"TimeService" depends on undefined module "timeservice_app_cert-legacy-um"

### ISSUE THREAD

**Issue by verNANDo57** [xiaomi-sdm660/android_vendor_xiaomi_sdm660-common#4]
"TimeService" depends on undefined module "timeservice_app_cert-legacy-um"

error: vendor/xiaomi/sdm660-common/Android.bp:189:1: "TimeService" depends on undefined module "timeservice_app_cert-legacy-um"
13:35:12 soong bootstrap failed with: exit status 1
make: *** [build/make/core/main.mk:21: run_soong_ui] Error 1

**Comment by rcstar6696** [comment]
Pick this commit to your rom qcom sepolicy source 

https://review.lineageos.org/c/LineageOS/android_device_qcom_sepolicy/+/266212

**Comment by Manish4586** [comment]
Pick this https://review.lineageos.org/c/LineageOS/android_device_qcom_sepolicy/+/266212
