### ISSUE TITLE
There is no Dialer_intermediates

### ISSUE THREAD

**Issue by verNANDo57** [xiaomi-sdm660/android_vendor_xiaomi_sdm660-common#5]
Something is missing:
ninja: error: "/out/host/common/obj/JAVA_LIBRARIES/javapoet-prebuilt-jar_intermediates/classes.jar', needed by '/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar', missing and no known rule to make it

**Comment by ctwoon** [comment]
That's your rom problem.
